- name: Cadastrar VM no NetBox
  hosts: all
  become: true
  gather_facts: true
  vars:
    netbox_url: "{{ lookup('env', 'NETBOX_API') }}"
    netbox_token: "{{ lookup('env', 'NETBOX_TOKEN') }}"
  tasks:

    - name: Obter hostname real da máquina
      ansible.builtin.command: hostname
      register: real_hostname

    - name: Cadastrar VM no NetBox
      netbox.netbox.netbox_device:
        netbox_url: "{{ netbox_url }}"
        netbox_token: "{{ netbox_token }}"
        data:
          name: "{{ real_hostname.stdout }}"
          device_type: "generic device"
          device_role: "server"
          status: active
        state: present
