- name: Coletar informações do sistema das VMs
  hosts: all
  become: true
  gather_facts: true

  tasks:

    - name: Mostrar informações de CPU
      ansible.builtin.shell: lscpu
      register: cpu_info

    - name: Mostrar informações de memória
      ansible.builtin.shell: free -h
      register: memory_info

    - name: Mostrar uso de disco
      ansible.builtin.shell: df -h /
      register: disk_info

    - name: Mostrar interfaces de rede
      ansible.builtin.shell: ip link show
      register: iface_info

    - name: Mostrar IP das interfaces
      ansible.builtin.shell: ip -4 addr show
      register: ip_info

    - name: Verificar status do sistema
      ansible.builtin.shell: uptime
      register: status_info

    - name: Exibir informações coletadas
      ansible.builtin.debug:
        msg:
          CPU: "{{ cpu_info.stdout }}"
          Memória: "{{ memory_info.stdout }}"
          Disco: "{{ disk_info.stdout }}"
          Interfaces: "{{ iface_info.stdout }}"
          IPs: "{{ ip_info.stdout }}"
          Status: "{{ status_info.stdout }}"
