- name: Hello VM Magalu
  hosts: all
  become: true
  gather_facts: true
  tasks:
    - name: Atualizar pacotes (Debian-based)
      apt:
        update_cache: yes
      when: ansible_os_family == "Debian"

    - name: Atualizar pacotes (RedHat-based)
      yum:
        name: '*'
        state: latest
      when: ansible_os_family == "RedHat"
